### ISSUE TITLE
Bot de Discord. Error al deplegar Heroku

### ISSUE THREAD

**Issue by AntonioJesusGarciaNieto** [EGC-decide-bailon/bot-dc#9]
La consola de heroku no muestra ningún fallo, aún así el sistema no responde.

**Comment by danbenveg** [comment]
Revisa el fichero Procfile. Prueba a configurar el dyno como "worker" y no como "web", que por lo visto apaga la aplicación después de una hora de inactividad. Te dejo un enlace de stackoverflow por si le quieres echar un ojo [https://stackoverflow.com/questions/51483462/heroku-discord-bot-is-offline](https://stackoverflow.com/questions/51483462/heroku-discord-bot-is-offline)

**Comment by AntonioJesusGarciaNieto** [comment]
Efectivamente, era por el Dyno, y el Procfile. Gracias. Ya está funcionando perfectamente.
